[2023-10-26T06:07:02.273+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_dag.load_data manual__2023-10-26T06:06:53.014001+00:00 [queued]>
[2023-10-26T06:07:02.289+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_dag.load_data manual__2023-10-26T06:06:53.014001+00:00 [queued]>
[2023-10-26T06:07:02.290+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 3
[2023-10-26T06:07:02.316+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): load_data> on 2023-10-26 06:06:53.014001+00:00
[2023-10-26T06:07:02.326+0000] {standard_task_runner.py:57} INFO - Started process 1964 to run task
[2023-10-26T06:07:02.329+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'etl_dag', 'load_data', 'manual__2023-10-26T06:06:53.014001+00:00', '--job-id', '376', '--raw', '--subdir', 'DAGS_FOLDER/tugaskel8_dag.py', '--cfg-path', '/tmp/tmpi03i_093']
[2023-10-26T06:07:02.333+0000] {standard_task_runner.py:85} INFO - Job 376: Subtask load_data
[2023-10-26T06:07:02.400+0000] {task_command.py:415} INFO - Running <TaskInstance: etl_dag.load_data manual__2023-10-26T06:06:53.014001+00:00 [running]> on host d73c1ff20372
[2023-10-26T06:07:02.790+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='kel8' AIRFLOW_CTX_DAG_ID='etl_dag' AIRFLOW_CTX_TASK_ID='load_data' AIRFLOW_CTX_EXECUTION_DATE='2023-10-26T06:06:53.014001+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-10-26T06:06:53.014001+00:00'
[2023-10-26T06:07:02.878+0000] {base.py:73} INFO - Using connection ID 'db_polusiudara' for task execution.
[2023-10-26T06:07:04.533+0000] {sql.py:418} INFO - Running statement: INSERT INTO hands_on_final VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s), parameters: (8637, 'Jakarta', 'US Diplomatic Post: Jakarta Central', None, 'ID', None, False, None, None, '2016-11-09T17:00:00+00:00', '2023-10-26T12:00:00+00:00', 60486)
[2023-10-26T06:07:04.596+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/tugaskel8_dag.py", line 55, in load_data
    hook.run("INSERT INTO hands_on_final VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)", parameters=(row['id'], row['city'], row['name'], row['entity'], row['country'], row['sources'], row['isMobile'], row['isAnalysis'], row['sensorType'], row['firstUpdated'], row['lastUpdated'], row['measurements']))
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 392, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 421, in _run_command
    cur.execute(sql_statement, parameters)
psycopg2.errors.InvalidTextRepresentation: invalid input syntax for type json
LINE 1: ..., false, NULL, NULL, '2016-11-09T17:00:00+00:00', '2023-10-2...
                                                             ^
DETAIL:  Expected end of input, but found "-10".
CONTEXT:  JSON data, line 1: 2023-10...

[2023-10-26T06:07:04.619+0000] {taskinstance.py:1398} INFO - Marking task as UP_FOR_RETRY. dag_id=etl_dag, task_id=load_data, execution_date=20231026T060653, start_date=20231026T060702, end_date=20231026T060704
[2023-10-26T06:07:04.637+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 376 for task load_data (invalid input syntax for type json
LINE 1: ..., false, NULL, NULL, '2016-11-09T17:00:00+00:00', '2023-10-2...
                                                             ^
DETAIL:  Expected end of input, but found "-10".
CONTEXT:  JSON data, line 1: 2023-10...
; 1964)
[2023-10-26T06:07:04.676+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-10-26T06:07:04.710+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
